# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190828_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thermistor_1', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_2', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_3', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_4', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_5', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_6', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_7', models.DecimalField(decimal_places=1, max_digits=4)),
                ('thermistor_8', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
