# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_temperature_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
